blueprint:
  name: Customizable Multi-Action Notification
  description: Sends notifications with multiple customizable actions.
  domain: automation
  input:
    doorbell_sensor:
      name: Doorbell Sensor
      description: Sensor that triggers the automation.
      selector:
        entity:
          domain: binary_sensor
    camera_entity:
      name: Camera Entity
      description: Camera for taking snapshots.
      selector:
        entity:
          domain: camera
    notification_targets:
      name: Notification Targets
      description: Devices to send notifications to.
      selector:
        target:
          entity:
            domain: mobile_app
          multiple: true
    custom_action_1:
      name: Custom Action 1
      description: First custom action URI.
      default: "reolink://open"
    custom_title_1:
      name: Custom Title 1
      description: Title for the first custom action.
      default: "View in Reolink App"

trigger:
  platform: state
  entity_id: !input 'doorbell_sensor'
  to: 'on'

action:
  - service: camera.snapshot
    target:
      entity_id: !input 'camera_entity'
    data:
      filename: '/config/www/doorbell_snapshot.jpg'
  - delay: '00:00:01'
  - repeat:
      count: "{{ expand('input.notification_targets') | count }}"
      sequence:
        - service: notify.mobile_app
          data:
            message: "Doorbell pressed!"
            data:
              image: '/local/doorbell_snapshot.jpg'
              actions:
                - action: "custom_action_1"
                  title: !input 'custom_title_1'
                  uri: !input 'custom_action_1'
                # Add more actions here
