blueprint:
  name: Doorbell Camera Notification
  description: Sends a camera snapshot as an actionable notification when the doorbell is pressed.
  domain: automation
  input:
    doorbell_sensor:
      name: Doorbell Sensor
      selector:
        entity:
          domain: binary_sensor
    camera_entity:
      name: Camera Entity
      selector:
        entity:
          domain: camera
    notification_target:
      name: Notification Target
      selector:
        device:
          integration: mobile_app
    lock_entity:
      name: Lock Entity
      selector:
        entity:
          domain: lock

trigger:
  platform: state
  entity_id: !input 'doorbell_sensor'
  to: 'on'

action:
  - service: camera.snapshot
    data:
      entity_id: !input 'camera_entity'
      filename: '/tmp/doorbell_camera_snapshot.jpg'

  - service: notify.mobile_app
    data:
      message: "Doorbell pressed!"
      data:
        image: '/tmp/doorbell_camera_snapshot.jpg'
        actions:
          - action: "fb1675493782511558://"
            title: "View Live Feed"
          - service: "lock.unlock"
            service_data:
              entity_id: !input 'lock_entity'
            title: "Unlock Door"
