blueprint:
  name: Doorbell Camera Notification
  description: Sends a camera snapshot as an actionable notification when the doorbell is pressed.
  domain: automation
  input:
    doorbell_sensor:
      name: Doorbell Sensor
      selector:
        entity:
          domain: binary_sensor
    snapshot_url:
      name: Snapshot URL
      description: Enter the URL to grab the camera snapshot from.
      selector:
        text: {}
    notification_target:
      name: Notification Target
      selector:
        device:
          integration: mobile_app
    lock_entity:
      name: Lock Entity
      selector:
        entity:
          domain: lock

trigger:
  platform: state
  entity_id: !input 'doorbell_sensor'
  to: 'on'

action:
  - service: shell_command.download_snapshot
    data:
      snapshot_url: !input 'snapshot_url'

  - service: notify.mobile_app
    data:
      message: "Doorbell pressed!"
      data:
        image: '/config/tmp/doorbell_camera_snapshot.jpg'
        actions:
          - action: "fb1675493782511558://"
            title: "View Live Feed"
          - service: "lock.unlock"
            service_data:
              entity_id: !input 'lock_entity'
            title: "Unlock Door"
