blueprint:
  name: Doorbell Camera Notification with Multiple Actions
  description: Sends a camera snapshot as an actionable notification with multiple actions when the doorbell is pressed.
  domain: automation
  input:
    doorbell_sensor:
      name: Doorbell Sensor
      description: Select the sensor that detects when your doorbell is pressed.
      selector:
        entity:
          domain: binary_sensor
    camera_entity:
      name: Camera Entity
      description: Choose the camera to take a snapshot.
      selector:
        entity:
          domain: camera
    notification_target:
      name: Notification Target
      description: Select the device to receive the notification.
      selector:
        device:
          integration: mobile_app
    additional_entity_one:
      name: Additional Entity One
      description: Select an additional entity for use in the automation.
      selector:
        entity: {}
    additional_entity_two:
      name: Additional Entity Two
      description: Select another additional entity for use in the automation.
      selector:
        entity: {}
    action_one:
      name: First Action
      description: Define the first custom action.
      default: ''
    action_one_title:
      name: First Action Title
      description: Title for the first action button.
      default: ''
    action_two:
      name: Second Action
      description: Define the second custom action.
      default: ''
    action_two_title:
      name: Second Action Title
      description: Title for the second action button.
      default: ''
    action_three:
      name: Third Action
      description: Define the third custom action.
      default: ''
    action_three_title:
      name: Third Action Title
      description: Title for the third action button.
      default: ''

trigger:
  platform: state
  entity_id: !input 'doorbell_sensor'
  to: 'on'

action:
  - service: camera.snapshot
    target:
      entity_id: !input 'camera_entity'
    data:
      filename: '/config/www/doorbell_snapshot.jpg'
  - delay: '00:00:01'  # Wait for the snapshot to be saved
  - service: notify.mobile_app
    target:
      device_id: !input 'notification_target'
    data:
      message: "Doorbell pressed!"
      data:
        image: '/local/doorbell_snapshot.jpg'
        actions:
          - action: !input 'action_one'
            title: !input 'action_one_title'
            condition: "{{ action_one != '' }}"
          - action: !input 'action_two'
            title: !input 'action_two_title'
            condition: "{{ action_two != '' }}"
          - action: !input 'action_three'
            title: !input 'action_three_title'
            condition: "{{ action_three != '' }}"
