blueprint:
  name: Doorbell Press Camera Snapshot Notification
  description: Send a notification with a camera snapshot to multiple devices when the doorbell is pressed.
  domain: automation
  input:
    camera_entity:
      name: Camera
      selector:
        entity:
          domain: camera
    notify_devices:
      name: Notify Devices
      selector:
        target:
          entity:
            domain: notify

trigger:
  - platform: state
    entity_id: binary_sensor.doorbell_visitor
    to: 'on'

action:
  - service: camera.snapshot
    target:
      entity_id: !input 'camera_entity'
    data:
      filename: '/tmp/doorbell_snapshot.jpg'
  - delay: 00:00:01  # Wait for the snapshot to be taken
  - service: notify.mobile_app
    target: !input 'notify_devices'
    data:
      message: "Doorbell pressed!"
      data:
        image: '/tmp/doorbell_snapshot.jpg'
        actions:
          - action: URI
            title: "Open Reolink App"
            uri: "fb1675493782511558://"  # Reolink app custom URI
          - action: DISMISS
            title: "Dismiss"
