blueprint:
  name: Doorbell Camera Notification with Customizable Actions
  description: Sends a camera snapshot as an actionable notification with customizable actions when the doorbell is pressed.
  domain: automation
  input:
    doorbell_sensor:
      name: Doorbell Sensor
      description: The sensor that triggers when the doorbell is pressed.
      selector:
        entity:
          domain: binary_sensor
    camera_entity:
      name: Camera Entity
      description: The camera to take a snapshot from.
      selector:
        entity:
          domain: camera
    notification_target:
      name: Notification Target
      description: The device to send the notification to.
      selector:
        device:
          integration: mobile_app
    action_one:
      name: First Action
      description: Custom action one (e.g., 'open_door').
      default: 'open_door'
    action_one_title:
      name: First Action Title
      description: Title for the first action button.
      default: 'Open Door'
    action_two:
      name: Second Action
      description: Custom action two (e.g., 'view_camera').
      default: 'view_camera'
    action_two_title:
      name: Second Action Title
      description: Title for the second action button.
      default: 'View Camera'

trigger:
  platform: state
  entity_id: !input 'doorbell_sensor'
  to: 'on'

action:
  - service: camera.snapshot
    target:
      entity_id: !input 'camera_entity'
    data:
      filename: '/config/www/doorbell_snapshot.jpg'
  - delay: '00:00:01'  # Wait for the snapshot to be saved
  - service: notify.mobile_app
    target:
      device_id: !input 'notification_target'
    data:
      message: "Doorbell pressed!"
      data:
        image: '/local/doorbell_snapshot.jpg'
        actions:
          - action: !input 'action_one'
            title: !input 'action_one_title'
          - action: !input 'action_two'
            title: !input 'action_two_title'
