blueprint:
  name: Doorbell Press Camera Snapshot Notification
  description: Send a notification with a camera snapshot to a selected device when the doorbell is pressed.
  domain: automation
  input:
    camera_entity:
      name: Camera
      selector:
        entity:
          domain: camera
    notify_device:
      name: Notify Device
      description: The device to send notifications to.
      selector:
        device:
          integration: mobile_app

trigger:
  - platform: state
    entity_id: binary_sensor.doorbell_visitor
    to: 'on'

action:
  - service: camera.snapshot
    target:
      entity_id: !input 'camera_entity'
    data:
      filename: '/tmp/doorbell_snapshot.jpg'
  - delay: 00:00:01  # Wait for the snapshot to be taken
  - service: notify.notify
    target:
      device_id: !input 'notify_device'
    data:
      message: "Doorbell pressed!"
      data:
        image: '/tmp/doorbell_snapshot.jpg'
        actions:
          - action: URI
            title: "Open Reolink App"
            uri: "fb1675493782511558://"  # Reolink app custom URI
          - action: DISMISS
            title: "Dismiss"
